-- MySQL Script generated by MySQL Workbench
-- 11/13/15 10:27:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema norm
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `norm` ;

-- -----------------------------------------------------
-- Schema norm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `norm` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `norm` ;

-- -----------------------------------------------------
-- Table `norm`.`clinical_trial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `norm`.`clinical_trial` ;

CREATE TABLE IF NOT EXISTS `norm`.`clinical_trial` (
  `id` CHAR(12) NOT NULL,
  `title` TEXT NULL COMMENT 'title: title of the study',
  `studytype` VARCHAR(45) NULL COMMENT 'studytype: type of study',
  PRIMARY KEY (`id`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `norm`.`eligibility_criteria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `norm`.`eligibility_criteria` ;

CREATE TABLE IF NOT EXISTS `norm`.`eligibility_criteria` (
  `id` INT NOT NULL,
  `clinical_trial_id` VARCHAR(12) NOT NULL,
  `inc_exc` INT NULL COMMENT 'type: inclusion or exclusion\n',
  `utterance` TEXT NULL COMMENT 'text: Utterance of the eligibility criteria',
  PRIMARY KEY (`id`, `clinical_trial_id`) ,
  INDEX `fk_eligibilitycriteria_clinicaltrial_idx` (`clinical_trial_id` ASC) ,
  CONSTRAINT `fk_eligibilitycriteria_clinicaltrial`
    FOREIGN KEY (`clinical_trial_id`)
    REFERENCES `norm`.`clinical_trial` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `norm`.`concept`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `norm`.`concept` ;

CREATE TABLE IF NOT EXISTS `norm`.`concept` (
  `sctid` VARCHAR(15) NOT NULL,
  `cui` VARCHAR(10) NULL,
  `name` VARCHAR(255) NULL,
  `semantic_type` VARCHAR(45) NULL COMMENT 'type: hierarchy in SNOMEDCT taxonomy',
  PRIMARY KEY (`sctid`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `norm`.`ec_concepts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `norm`.`ec_concepts` ;

CREATE TABLE IF NOT EXISTS `norm`.`ec_concepts` (
  `eligibility_criteria_id` INT NOT NULL,
  `clinical_trial_id` VARCHAR(12) NOT NULL,
  `concept_sctid` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`eligibility_criteria_id`, `clinical_trial_id`, `concept_sctid`) ,
  INDEX `fk_eligibility_criteria_has_concept_concept1_idx` (`concept_sctid` ASC) ,
  INDEX `fk_eligibility_criteria_has_concept_eligibility_criteria1_idx` (`eligibility_criteria_id` ASC, `clinical_trial_id` ASC) ,
  CONSTRAINT `fk_eligibility_criteria_has_concept_eligibility_criteria1`
    FOREIGN KEY (`eligibility_criteria_id` , `clinical_trial_id`)
    REFERENCES `norm`.`eligibility_criteria` (`id` , `clinical_trial_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eligibility_criteria_has_concept_concept1`
    FOREIGN KEY (`concept_sctid`)
    REFERENCES `norm`.`concept` (`sctid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
